#include "ListasTAD.h"
/**
* Enunciado:
*/
//#define DEPURACION

Principal
Lista l,l2;
l.agregaEle(1);
l.agregaEle(2.2);
l.agregaEle('3');
l.agregaEle("4");
l.enLista(VERDADERO);
l.enLista(6.6);
l.enLista('7');
l.enLista("8");
l[7].agregaEle(9.9);
l[7].agregaEle(10);
//pausa;
l[7].enLista("once");
l[7][3].agregaEle("doce");
l[7][3].enLista(13);
//l.muestra();
//l[7].muestra();
//l(7)(1).muestra();
//l[7](1).muestra();
l.muestra();
//mostrar << "----------------" << salto;
//l[7].muestra();
//mostrar << "----------------" << salto;
//(l[7][3]).muestra();
//mostrar << "----------------" << salto;
//(l[7][3][0]).muestra();
//l[7][0][0].muestra();
//l[7][1][0].muestra();
//pausa;
l2 = l;
mostrar << "Listas "<< fSi(l ES l2,"iguales","distintas") << salto;
l.borraEle(2);
l.borraEle(6);
l.muestra();
l[7].borraLista();
//l[7][1]->enLista(10.10);
//l[7][1]->enLista(11.11);
//l.muestra();
//pausa;
//Bloque
//l[0]++;
//++l[0];
//--l[0];
//--l[0];
//l[0]--;
//l[0]--;
//si(l[3].cualTipo() ES LISTA) l[3].enLista(9);
//si(l[4].cualTipo() ES LISTA) l[4].enLista(10);
//finBloque
//l.enLista(4.4);
//l.agregaEle(3.3333);
//l[1].enLista(1234);
//l[3] = 999;
////l[2].vale().subL->agregaEle(888);
////l[2].vale().subL->agregaEle("Adentro");
//l[2].agregaEle(888);
//l[2].agregaEle("Adentro");
//l[1].enLista();
//l.enLista("Adentro");
//l[1].muestra();
//l(1).enLista(888);
//l(1).muestra();
//mostrar << "-------" << salto;
//l2 = l;
////l2.muestra();
//l.insertaEle(l2);
//l.agregaEle(l2);
//l2.muestra();
//l.agregaEle("Apa...");
//l.muestra();
//l.agregaEle(11.1);
//l.agregaEle('1');
//l.enLista(2.2);
//Lista li = l;
//li.muestra();
//li.enLista(999L);
//li.enLista(2.34d);
//li.agregaEle(3.4);
//li.muestra();
//li.insertaEle(-1.1);
//li.muestra();
//li[1] = {7.7};
//li.muestra();
//li[1] = Lista(4.4d);
//li.muestra();
//li[1] = 1234l;
//li.intercalaEle(2.2,1);
//li.intercalaEle(Lista(2.01d),1);
//li.muestra();
////li.agregaEle(20l);
////li.agregaEle(Lista(3.3));
////li.insertaEle(Lista(1.1));
////li.agregaEle(3l);
////////li[2]->agregaEle(4l);
//////li[2]->agregaEle(5l);
//l = li;
//pausa;
//li.borraLista();
//li.muestra();
//l.muestra();
//l.borraLista();
////l.~Lista();
////l.muestra();
//pausa;
//li.muestra();
//l.primero().muestra();
//l.menosPrimero().muestra();
//l.menosPrimero().menosPrimero().muestra();
//l.ultimo().muestra();
//l.men en donar sangre y plaquetas para Natacha Rodríguez. Soy Carlos, el papá.osUltimo().muestra();
//l.menosUltimo().menosUltimo().muestra();
//delete [] li[0];
//mostrar << "Memoria usada: " << memIni-memoria() << salto;
//li[2]->muestra();
//pausa;
//li.muestra();
//pausa;
//li.muestra();
//pausa;
//li[0]->agregaEle((doble)1.2);
//li.muestra();
//li[0]->agregaEle(Lista((doble)3.56));
//li.muestra();
//pausa;
//li[0]->agregaEle((doble)33.56);
//li.muestra();
//li[0]->muestra();
//li[1] = (doble)091.1;
//(li[0])[0] = (doble)654.3;
//li.muestra();
////l2 = li;
////l2.muestra();
//mostrar << salto;
//li[0].agregaEle((doble)2.1);
//li.muestra();
finPrincipal
